[package]
name = "dxlib"
version = "0.1.0"
authors = ["Tomoya Ishii <tmy1997530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dxlib-sys = { path = "../dxlib-sys" }
thiserror = "1.0.24"
anyhow = "1.0.40"
libloading = "0.7.0"
